def get_noise_folders() -> set[str]:
    """Generic noise folders"""
    return {
        # version control
        ".git",
        ".hg",
        ".svn",
        # build output
        "artifacts",
        "bin",
        "build",
        "debug",
        "dist",
        "generated",
        "log",
        "logs",
        "obj",
        "out",
        "release",
        # general cache
        ".cache",
        "temp",
        "tmp",
        # python
        "__generated__",
        "__pycache__",
        "__pypackages__",
        ".eggs",
        ".ipynb_checkpoints",
        ".mypy_cache",
        ".nox",
        ".pdm-build",
        ".pixi",
        ".pyre",
        ".pytest_cache",
        ".pytype",
        ".ruff_cache",
        ".tox",
        ".venv",
        "develop-eggs",
        "eggs",
        "htmlcov",
        "lib-cov",
        "pip-wheel-metadata",
        "sdist",
        "venv",
        "wheels",
        # javascript / node
        ".angular",
        ".cache-loader",
        ".eslintcache",
        ".next",
        ".npm",
        ".nuxt",
        ".nx",
        ".nyc_output",
        ".output",
        ".parcel-cache",
        ".playwright",
        ".pnpm-store",
        ".sass-cache",
        ".storybook-cache",
        ".svelte-kit",
        ".swc",
        ".turbo",
        ".vite",
        ".webpack",
        "bower_components",
        "jspm_packages",
        "node_modules",
        "playwright-report",
        "storybook-static",
        "web_modules",
        # c / c++
        "_deps",
        "CMakeFiles",
        "cmake-build-debug",
        "cmake-build-release",
        # java / kotlin
        ".grunt",
        "target",
        # php / go
        "vendor",
        # swift / ios
        "DerivedData",
        "Pods",
        # dart / flutter
        ".dart_tool",
        ".pub-cache",
        # scala
        ".bloop",
        # haskell
        ".stack-work",
        "dist-newstyle",
        # infrastructure / cloud
        ".serverless",
        ".terraform",
        "cdk.out",
        # static site generators
        ".docusaurus",
        ".jekyll-cache",
        "_build",
        "_site",
        # data science / ml
        ".mlruns",
        "wandb",
        # coverage
        "coverage",
    }
